language: ruby
rvm:
  - 1.9.3

env:
  - DB=sqlite

script:
  - export RAILS_ENV=test 
  - export RAILS_ENV=test bundle exec rake db:drop
  - export RAILS_ENV=test bundle exec rake db:create 
  - export RAILS_ENV=test bundle exec rake db:migrate 
  - bundle exec rake db:test:prepare
  - bundle exec rspec

