language: ruby
rvm:
  - 1.9.3

env:
  - DB=sqlite

script:
  - RAILS_ENV=test bundle exec rake db:test:prepare
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rspec spec/models/release_spec.rb spec/models/cashier_spec.rb

