language: ruby
rvm:
  - 1.9.3

env:
  - DB=sqlite

script:
  - rake db:test:clone_structure
  - rake db:migrate
  - bundle exec rake db:test:prepare
  - bundle exec rspec spec/models/release_spec.rb spec/models/cashier_spec.rb

