language: ruby
rvm:
  - 1.9.3

env:
  - DB=sqlite

script:
  - bundle
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec db:test:prepare
  - bundle exec rspec
before_script:
  - bundle exec rake db:create RAILS_ENV=test
